# Generated by Django 5.0.6 on 2024-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
