# Generated by Django 5.0.6 on 2024-07-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_userdata_is_synthetic_alter_userdata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_synthetic',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
