# Generated by Django 5.0.6 on 2024-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_userdata_is_synthetic_alter_userdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='leaked',
            field=models.BooleanField(default=False),
        ),
    ]
