# Generated by Django 5.0.6 on 2024-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_userdata_leaked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
